version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: react-frontend/Dockerfile
    image: simple_java_app
    container_name: front_end_crud_java
    ports:
      - "3000:3000"  # React app runs on 3000
    networks:
      - crud_java
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: springboot-backend/Dockerfile
    container_name: backend_end_crud_java
    ports:
      - "8080:8080"  # Spring Boot runs on 8080
    networks:
      - crud_java
    depends_on:
      - server

  server:
    image: nginx:alpine
    container_name: nginx_con_simple_crud_java_Springboot
    ports:
      - "80:80"  # Nginx listens on 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the nginx.conf
    networks:
      - crud_java

networks:
  crud_java:
    driver: bridge
