version: "3"

services:
  backend:
    build:
      context: ./springboot-backend
      dockerfile: Dockerfile
    container_name: backend_end_crud_java
    ports:
      - "8080:8080"
    networks:
      - crud_java

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    image: frontend_image
    container_name: front_end_crud_java
    networks:
      - crud_java
    depends_on:
      - backend

  server:
    image: nginx:alpine
    container_name: nginx_con_simple_crud_java_Springboot
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - crud_java
    depends_on:
      - frontend
      - backend

networks:
  crud_java:
    driver: bridge
